#cloud-config
# Cloud config for application servers

runcmd:
  # Install docker
  - curl -sSL https://get.docker.com | sudo sh
  - 'docker swarm join --token <Your swarm tocken here> <Docker swarm master IP>:2377'
